# Generated by Django 2.1.3 on 2018-11-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ascensor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='idAscensor',
            new_name='identificadorAscensor',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='orden',
            name='fallas',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='piezas',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='reparaciones',
            field=models.TextField(blank=True),
        ),
    ]
