# Generated by Django 2.1.3 on 2018-11-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ascensor', '0002_auto_20181123_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apellidos',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='orden',
            name='horaInicio',
            field=models.TimeField(verbose_name='Hora de inicio'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='horaTermino',
            field=models.TimeField(verbose_name='Hora de termino'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='identificadorAscensor',
            field=models.CharField(max_length=20, verbose_name='Identificador ascensor'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='modeloAscensor',
            field=models.CharField(max_length=20, verbose_name='Modelo del ascensor'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='nombreReceptor',
            field=models.CharField(max_length=50, verbose_name='Nombre del receptor'),
        ),
    ]
