# Generated by Django 2.1.3 on 2018-12-08 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ascensor', '0002_auto_20181206_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='tecnico',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Técnico'),
            preserve_default=False,
        ),
    ]
